/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassClassIdIndexRouteImport } from './routes/class.$classId.index'
import { Route as ClassClassIdSituationRouteImport } from './routes/class.$classId.situation'
import { Route as ClassClassIdParcoursRouteImport } from './routes/class.$classId.parcours'
import { Route as ClassClassIdHistoriqueRouteImport } from './routes/class.$classId.historique'
import { Route as ClassClassIdStudentStudentIdRouteImport } from './routes/class.$classId.student.$studentId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdIndexRoute = ClassClassIdIndexRouteImport.update({
  id: '/class/$classId/',
  path: '/class/$classId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdSituationRoute = ClassClassIdSituationRouteImport.update({
  id: '/class/$classId/situation',
  path: '/class/$classId/situation',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdParcoursRoute = ClassClassIdParcoursRouteImport.update({
  id: '/class/$classId/parcours',
  path: '/class/$classId/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdHistoriqueRoute = ClassClassIdHistoriqueRouteImport.update({
  id: '/class/$classId/historique',
  path: '/class/$classId/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdStudentStudentIdRoute =
  ClassClassIdStudentStudentIdRouteImport.update({
    id: '/class/$classId/student/$studentId',
    path: '/class/$classId/student/$studentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/class/$classId/historique': typeof ClassClassIdHistoriqueRoute
  '/class/$classId/parcours': typeof ClassClassIdParcoursRoute
  '/class/$classId/situation': typeof ClassClassIdSituationRoute
  '/class/$classId/': typeof ClassClassIdIndexRoute
  '/class/$classId/student/$studentId': typeof ClassClassIdStudentStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/class/$classId/historique': typeof ClassClassIdHistoriqueRoute
  '/class/$classId/parcours': typeof ClassClassIdParcoursRoute
  '/class/$classId/situation': typeof ClassClassIdSituationRoute
  '/class/$classId': typeof ClassClassIdIndexRoute
  '/class/$classId/student/$studentId': typeof ClassClassIdStudentStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/class/$classId/historique': typeof ClassClassIdHistoriqueRoute
  '/class/$classId/parcours': typeof ClassClassIdParcoursRoute
  '/class/$classId/situation': typeof ClassClassIdSituationRoute
  '/class/$classId/': typeof ClassClassIdIndexRoute
  '/class/$classId/student/$studentId': typeof ClassClassIdStudentStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/class/$classId/historique'
    | '/class/$classId/parcours'
    | '/class/$classId/situation'
    | '/class/$classId/'
    | '/class/$classId/student/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/class/$classId/historique'
    | '/class/$classId/parcours'
    | '/class/$classId/situation'
    | '/class/$classId'
    | '/class/$classId/student/$studentId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/class/$classId/historique'
    | '/class/$classId/parcours'
    | '/class/$classId/situation'
    | '/class/$classId/'
    | '/class/$classId/student/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ClassClassIdHistoriqueRoute: typeof ClassClassIdHistoriqueRoute
  ClassClassIdParcoursRoute: typeof ClassClassIdParcoursRoute
  ClassClassIdSituationRoute: typeof ClassClassIdSituationRoute
  ClassClassIdIndexRoute: typeof ClassClassIdIndexRoute
  ClassClassIdStudentStudentIdRoute: typeof ClassClassIdStudentStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId/': {
      id: '/class/$classId/'
      path: '/class/$classId'
      fullPath: '/class/$classId/'
      preLoaderRoute: typeof ClassClassIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId/situation': {
      id: '/class/$classId/situation'
      path: '/class/$classId/situation'
      fullPath: '/class/$classId/situation'
      preLoaderRoute: typeof ClassClassIdSituationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId/parcours': {
      id: '/class/$classId/parcours'
      path: '/class/$classId/parcours'
      fullPath: '/class/$classId/parcours'
      preLoaderRoute: typeof ClassClassIdParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId/historique': {
      id: '/class/$classId/historique'
      path: '/class/$classId/historique'
      fullPath: '/class/$classId/historique'
      preLoaderRoute: typeof ClassClassIdHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId/student/$studentId': {
      id: '/class/$classId/student/$studentId'
      path: '/class/$classId/student/$studentId'
      fullPath: '/class/$classId/student/$studentId'
      preLoaderRoute: typeof ClassClassIdStudentStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ClassClassIdHistoriqueRoute: ClassClassIdHistoriqueRoute,
  ClassClassIdParcoursRoute: ClassClassIdParcoursRoute,
  ClassClassIdSituationRoute: ClassClassIdSituationRoute,
  ClassClassIdIndexRoute: ClassClassIdIndexRoute,
  ClassClassIdStudentStudentIdRoute: ClassClassIdStudentStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
